import Header from "@/components/header/header";
export const metadata = {
  title: "Portfolio",
  description: "Generated by Next.js",
};
import "./globals.css";
export default function RootLayout({ children }) {
  console.log("hello world");

  return (
    <html lang="en">
      <body className="bg-[#292F36]">
        <header className="bg-[#292F36] container">
          <Header />
        </header>
        <main>{children} </main>
      </body>
    </html>
  );
}
